import React from "react";

const Disclaimer = () => {
  return (
    <div className="bg-[#FFFBE6] border-t border-yellow-200">
      <div className="max-w-7xl mx-auto px-6 py-5">

        <div className="flex items-start gap-3">
          {/* Warning Icon */}
          <span className="text-yellow-600 text-lg mt-[2px]">
            ⚠️
          </span>

          {/* Text */}
          <div>
            <h4 className="text-sm font-semibold text-yellow-800 mb-1">
              Disclaimer
            </h4>

            <p className="text-sm text-gray-800 leading-relaxed">
              The results generated by the A2G RAM Tool are based on the{" "}
              <strong>Recycling Assessment Methodology (RAM)</strong> developed
              by <strong>DEFRA and WRAP</strong> under the UK Packaging EPR
              Regulations. While the tool provides a robust and
              regulation-aligned assessment, final compliance decisions may
              vary. For a second review or further guidance, please contact us.
            </p>
          </div>
        </div>

      </div>
    </div>
  );
};

export default Disclaimer;
